# fly.toml app configuration file generated for yarnballs-bitter-field-3543 on 2025-06-27T23:32:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yarnballs-bitter-field-3543'
primary_region = 'ewr'
kill_signal = 'SIGTERM'

[build]
  [build.args]
    # PHX_HOST = 'yarnballs-bitter-field-3543.fly.dev'
    PHX_HOST = 'yarnballs.ggyo.xyz'

[env]
  # PHX_HOST = 'yarnballs-bitter-field-3543.fly.dev'
  PHX_HOST = 'yarnballs.ggyo.xyz'
  PORT = '8080'
  POOL_SIZE = '5'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
